version: 2.1

defaults: &defaults
  docker:
    - image: vuejs/ci

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: yarn --frozen-lockfile

jobs:
  <<: *defaults
  test:
    steps:
      - checkout
      - *install_deps

workflows:
  node-tests:
    jobs:
      - test
